#Check if JBoss already exists

- name: Check JBoss
  stat:
    path: "{{ item }}"
  with_items:
    - "/opt/jboss/server/{{ instancename }}/conf/jboss-service.xml"
    - "/opt/jboss/server/{{ instancename }}/deploy/jboss-web.deployer/server.xml"
    - "/opt/jboss/server/{{ instancename }}/conf/java_opts.conf"
  register: check_file

#Grabbing and unarchiving JBoss from custom source link into specified dir.
- name: Unarchive JBoss 5
  unarchive:
    src: http://cooperacao.info.ufrn.br/download/jboss-5.1.0.GA.tar.gz
    dest: /opt/jboss
    extra_opts: [--strip-components=1]
    remote_src: yes
    validate_certs: no
  when:
    - check_file.results[0].stat.exists == false
      and check_file.results[1].stat.exists == false
      and check_file.results[2].stat.exists == false
