#Check if JBoss already exists

- name: Check JBoss Files
  stat:
    path: "{{ item }}"
  with_items:
    - "/opt/jboss"
    - "/opt/jboss/server/{{ instancename }}/conf/jboss-service.xml"
    - "/opt/jboss/server/{{ instancename }}/deploy/jboss-web.deployer/server.xml"
    - "/opt/jboss/server/{{ instancename }}/conf/java_opts.conf"
  register: check_file

#Changing owner and group in case dir exists
- name: Change owner and group for JBoss Dir
  file:
    recurse: yes
    path: /opt/jboss
    owner: sistemas
    group: sistemas
    state: directory
  when:
    - check_file.results[0].stat.exists == true

- name: Rename JBoss Instance Directory
  command: mv /opt/jboss/server/default /opt/jboss/server/{{ instancename }}
  become: yes
  when:
    - check_file.results[0].stat.exists == true and check_file.results[3].stat.exists == false

- name: Define values for java_opts
  template:
    src: java_opts.conf.j2
    dest: /opt/jboss/server/{{ instancename }}/conf/java_opts.conf
  when:
    - check_file.results[3].stat.exists == false

- name: Define values for server.xml
  template:
    src: server.xml.j2
    dest: /opt/jboss/server/{{ instancename }}/deploy/jboss-web.deployer/server.xml
  when:
    - check_file.results[2].stat.exists == false

- name: Define values for jboss-service.xml
  template:
    src: jboss-service.xml.j2
    dest: /opt/jboss/server/{{ instancename }}/conf/jboss-service.xml
  when:
    - check_file.results[1].stat.exists == false