
- name: check for Java
  command: java -version
  register: result
  ignore_errors: True
  changed_when: false

- name: Download JDK6
  get_url:
    url: https://cooperacao.info.ufrn.br/download/jdk-6u45-linux-x64-rpm.bin
    validate_certs: no
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"
    dest: /tmp/
    mode: "u+x"
  when: result|failed or result|skipped

- name: Run JDK RPM
  shell: /tmp/jdk-6u45-linux-x64-rpm.bin
  when: result|failed or result|skipped