
- group:
    name: sistemas
    state: present

- name: Create user sistemas
  user:
    name: sistemas
    group: sistemas
    shell: /bin/bash
    home: /opt/sistemas/
    state: present
  ignore_errors: yes

- name: Creates directory sistemas
  file:
    path: /opt/sistemas
    state: directory

- name: Creates directory jboss
  file:
    path: /opt/jboss
    state: directory